# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

  config:
    activate:
      on-profile: ci,test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: root
    password: root

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: DEBUG
        transaction: INFO
        interceptor: TRACE




